### ISSUE TITLE
Duplicate records

### ISSUE THREAD

**Issue by Aviel212** [yardenshoham/coin-trend-notifier#17]
Duplicate users has been added to the database with no counter action from the server's or the database's side. 

![image](https://user-images.githubusercontent.com/29763426/83874535-512dfa00-a73e-11ea-95f9-0832632f3999.png)

**Comment by yardenshoham** [comment]
Nope

**Comment by Aviel212** [comment]
It is after double checking

**Comment by Aviel212** [comment]
Solved ![image](https://user-images.githubusercontent.com/29763426/83875409-b6361f80-a73f-11ea-82f0-b311ec9cc386.png)
