### ISSUE TITLE
Add property for Event and add another endpoint to server

### ISSUE THREAD

**Issue by Aviel212** [yardenshoham/coin-trend-notifier#18]
While developing the client side I was encountered with a problem where I tried to display the price of the asset according to the time the event was fired and comapre it to the current asset's price. In order to be able to analyze my the program's score and give better UX to the client and to be able to give the client wider actions to perform. 
![image](https://user-images.githubusercontent.com/29763426/83875039-1ed0cc80-a73f-11ea-8003-aa32c506f7cd.png)

**Comment by yardenshoham** [comment]
This was not in the requirements.
